### ISSUE TITLE
Is this can be used in ReactNative project?

### ISSUE THREAD

**Issue by dubiao** [NordicSemiconductor/pc-nrf-dfu-js#41]
Due to some reasons, we can not use native code in our reactnative project. Is this lib can be used in that kind of project??
Or, is it transplantable to rn projects?

In this repository, said it only support for some USB SDFU devices, but it contains a `Noble` `TransportPrn`, which seems to be used for BLE. How to use it ?

Thanks for your great job.

**Comment by chunfantasy** [comment]
Hi @dubiao, the scope of this repo is providing DFU (Device Firmware Upgrade) via USB CDC ACM transport for Nordic devices. We have not cleaned the code enough though, sorry for the misleading.
We will create task for cleaning it soon.

If you want to do DFU through BLE, I suggest you to use [pc-ble-dirver-js](https://github.com/NordicSemiconductor/pc-ble-driver-js)
If you have any questions regarding how to use it, we welcome you to ask questions at https://devzone.nordicsemi.com/

Since this is not an issue, I close it.

**Comment by dubiao** [comment]
> If you want to do DFU through BLE, I suggest you to use pc-ble-dirver-js

I want use BLE DFU on Android / iOS in ReactNative project . I think the project`pc-ble-dirver.js` is not adapted for this, is it?

**Comment by chunfantasy** [comment]
No, it is used for the PC side. The supported platforms are Windows, Linux and macOS.
